name: pixelarticons
description: "Pixel Art Icons made simple for Flutter, powered by pixelarticons and fontify"
version: 0.4.0
homepage: https://github.com/alexrintt/pixelarticons
pixelarticons_version: v1.7.0
repository: https://github.com/alexrintt/pixelarticons
issue_tracker: https://github.com/alexrintt/pixelarticons/issues
documentation: https://github.com/alexrintt/pixelarticons

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.7.2

flutter:
  fonts:
    - family: Pixel Art Icons
      fonts:
        - asset: fonts/pixelarticons.otf

fontify:
  input_svg_dir: "release/svg/"
  output_font_file: "fonts/pixelarticons.otf"

  output_class_file: "lib/pixel.dart"
  class_name: "Pixel"
  indent: 2
  package: pixelarticons

  font_name: "Pixel Art Icons"
  normalize: true
  ignore_shapes: true

  recursive: true
  verbose: false
